call pathogen#infect()
filetype on
syntax on
set background=dark
set t_Co=256
let g:solarized_termcolors=256
colorscheme solarized
set nocompatible
set ai
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set nu
set incsearch
set hlsearch
set ruler
set showcmd
set backspace=indent,eol,start
set nowrap
